java -classpath ./bin Silc < test01.sil
java -classpath ./bin Silc < test02.sil
java -classpath ./bin Silc < test03.sil
java -classpath ./bin Silc < test04.sil
java -classpath ./bin Silc < test05.sil
java -classpath ./bin Silc < test06.sil
java -classpath ./bin Silc < test07.sil
java -classpath ./bin Silc < test08.sil
java -classpath ./bin Silc < test09.sil
java -classpath ./bin Silc < test10.sil
java -classpath ./bin Silc < test11.sil
java -classpath ./bin Silc < test12.sil
java -classpath ./bin Silc < test13.sil
java -classpath ./bin Silc < test14.sil