#!/bin/sh

for file in *.clove
do
  cmdOutput=$(java -classpath ../bin Clove < "$file")
  snapshot=$(<"./snapshots/$file".snapshot)

  if [ "$snapshot" == "$cmdOutput" ]; then
    echo ""$file": PASS"
  else
    echo ""$file": FAIL <--"
  fi
done
