#!/bin/sh
echo "=== Test01.sil ==="
java -classpath ./bin:./lib/* Silt < test01.sil
echo "=== Test02.sil ==="
java -classpath ./bin:./lib/* Silt < test02.sil
echo "=== Test03.sil ==="
java -classpath ./bin:./lib/* Silt < test03.sil
echo "=== Test04.sil ==="
java -classpath ./bin:./lib/* Silt < test04.sil
echo "=== Test05.sil ==="
java -classpath ./bin:./lib/* Silt < test05.sil
echo "=== Test06.sil ==="
java -classpath ./bin:./lib/* Silt < test06.sil
echo "=== Test07.sil ==="
java -classpath ./bin:./lib/* Silt < test07.sil
echo "=== Test08.sil ==="
java -classpath ./bin:./lib/* Silt < test08.sil
echo "=== Test09.sil ==="
java -classpath ./bin:./lib/* Silt < test09.sil
echo "=== Test10.sil ==="
java -classpath ./bin:./lib/* Silt < test10.sil
echo "=== Test11.sil ==="
java -classpath ./bin:./lib/* Silt < test11.sil
echo "=== Test12.sil ==="
java -classpath ./bin:./lib/* Silt < test12.sil
echo "=== Test13.sil ==="
java -classpath ./bin:./lib/* Silt < test13.sil
echo "=== Test14.sil ==="
java -classpath ./bin:./lib/* Silt < test14.sil
