java -classpath ./bin:./lib/* Silt < test01.sil
java -classpath ./bin:./lib/* Silt < test02.sil
java -classpath ./bin:./lib/* Silt < test03.sil
java -classpath ./bin:./lib/* Silt < test04.sil
java -classpath ./bin:./lib/* Silt < test05.sil
java -classpath ./bin:./lib/* Silt < test06.sil
java -classpath ./bin:./lib/* Silt < test07.sil
java -classpath ./bin:./lib/* Silt < test08.sil
java -classpath ./bin:./lib/* Silt < test09.sil
java -classpath ./bin:./lib/* Silt < test10.sil
java -classpath ./bin:./lib/* Silt < test11.sil
java -classpath ./bin:./lib/* Silt < test12.sil
java -classpath ./bin:./lib/* Silt < test13.sil
java -classpath ./bin:./lib/* Silt < test14.sil