java -classpath ../bin Dumb < test01.dumb
java -classpath ../bin Dumb < test02.dumb
java -classpath ../bin Dumb < test03.dumb
java -classpath ../bin Dumb < test04.dumb
java -classpath ../bin Dumb < test05.dumb
java -classpath ../bin Dumb < test06.dumb
java -classpath ../bin Dumb < test07.dumb
java -classpath ../bin Dumb < test08.dumb
java -classpath ../bin Dumb < test09.dumb
java -classpath ../bin Dumb < test10.dumb
java -classpath ../bin Dumb < test11.dumb
java -classpath ../bin Dumb < test12.dumb
java -classpath ../bin Dumb < test13.dumb
java -classpath ../bin Dumb < test14.dumb
java -classpath ../bin Dumb < test15.dumb
java -classpath ../bin Dumb < test16.dumb
java -classpath ../bin Dumb < test17.dumb
java -classpath ../bin Dumb < test18.dumb
java -classpath ../bin Dumb < test19.dumb
java -classpath ../bin Dumb < test20.dumb
