#!/bin/sh

function run() {
	# "${@:2}" -- all arguments starting from 2.
	java -classpath ../bin Clove < "$1" "${@:2}"
}


for file in *.clove
do
	echo "============ "$file" ============"

	if [ "$file" == "random-argument.clove" ]; then
		run $file very random arguments
	else
		run $file
	fi

	echo ""
	echo ""
	echo ""
done
