name: Unit and Integration Tests

on:
  push:
    paths:
      - '.github/workflows/unit-and-integration-tests.yml'
      - 'Clove/gradle/**'
      - 'Clove/src/**'
      - 'Clove/build.gradle'
      - 'Clove/gradle.properties'
      - 'Clove/settings.gradle'

env:
  GRADLE_CACHE: 'cache-gradle'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    working-directory: ./Clove
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64

      - name: Grant Gradle wrapper sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build --info

      - name: Run unit tests
        run: ./gradlew test --info

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-20.04
    working-directory: ./Clove
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64

      - name: Grant Gradle wrapper sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build --info

      - name: Run integration tests
        run: ./gradlew integrationTest --info
